services:
  dev:
    container_name: webserv
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "../"
        target: "/webserv"
    command: /bin/sh -c "tail -f /dev/null"
