server {
    listen 6666 default_server;
    server_name _;

    root ./www/html;
    client_max_body_size 10M;

    error_page 405 /405.html;
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    keepalive_timeout 75s;

    location / {
        index index.html;
        autoindex on;
        limit_except GET POST DELETE {
            deny all;
        }
    }

    location /uploads {
        autoindex on;
        client_body_temp_path ./www/uploads;
        limit_except PUT DELETE GET {
            deny all;
        }
    }

    location ~ \.py$ {
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME ./cgi-bin$fastcgi_script_name;
    }

    location /redirect {
        return 301 http://example.com;
    }
}

server {
    listen 7777;
    server_name example.com;

    root ./www/example;
    client_max_body_size 500k;

    keepalive_timeout 60s;

    location / {
        index index.html index.htm;
        autoindex on;
        limit_except GET {
            deny all;
        }
    }
}
